### PR TITLE
Feature/milestone 4

### PR DESCRIPTION
**Pull request by martin-cervantes1**
:heavy_check_mark: Create the CHANGE_FILTER action in actions/index.js
:heavy_check_mark: Create a filter.js reducer which modifies filter in the Redux store. default to All.
:heavy_check_mark: Implement the CategoryFilter component
:heavy_check_mark: Implement the handleFilterChange method which modifies the filter state in the Redux store.
:heavy_check_mark: Implement a conditional method which decides which books should be shown in the table depending on the filter value from Redux store.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @mcervantes71 
### You have done well so far :clap: You have a few issues to be fixed:-
- [x] There are errors with the linting when I run `npx eslint .` command, kindly fix this issues. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/react-redux)
- [x] Do not change the files configuration as provided by Microverse i.e .stylelintrc.json, .eslintrc.json and github action action linters.yml
- [x] Also scripts like start is not working, kindly find the error and fix
### Make the changes and submit the project for another code review. Good luck.
- Happy coding!

**Comment by martin-cervantes1** [comment]
:heavy_check_mark: Change and update configuration files
:heavy_check_mark: Fix linter errors

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nicely done. You have made the changes suggested regarding the eslint file. However, we still have errors. Please fix all errors and make sure everything passes before re-submitting for another review.

### Martin Afani

**Comment by martin-cervantes1** [comment]
# local enviroment
I update eslint-plugin-import from 2.20.2 to 2.22.1 

image

# node_modules

image

# github

image

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Change required🛑
The cause of the eslint error is strange to me, it points to node_module meanwhile it is not committed so I wonder why the error is being raised, I have not come across this type of error before, so Kindly try to resolve the error by posting the error in the student channel or raised a ticket for help and let us see how it goes.
> These things can be frustrating sometimes but trust me, you end up learning a lot😇.
#### Happy coding😎
Addo Forison

**Comment by martin-cervantes1** [comment]
:heavy_check_mark: Fix eslint errors

**Review by Torres-ssf — APPROVED** [review]
### Milestone Approved :+1: 
Hi @mcervantes71 :hand: 
Awesome job implementing the requested changes :clap: 
Your PR is ready to merge.

Happy coding :computer: 
**Sergio Torres**

**Pull request merged**
